# Generated by Django 6.0.6 on 2026-06-11 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='signins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sellm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fresh Milk', 'Fresh Milk'), ('Pure Ghee', 'Pure Ghee'), ('Paneer & Cheese', 'Paneer & Cheese'), ('Curd & Yogurt', 'Curd & Yogurt'), ('Butter & Cream', 'Butter & Cream'), ('Family Combo', 'Family Combo')], max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('gallery_1', models.ImageField(upload_to='images/')),
                ('gallery_2', models.ImageField(upload_to='images/')),
                ('gallery_3', models.ImageField(upload_to='images/')),
                ('video_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('stock_status', models.CharField(choices=[('In stock', 'In stock'), ('Only few left', 'Only few left'), ('Out of stock', 'Out of stock'), ('Pre-order', 'Pre-order')], max_length=100)),
                ('badge', models.CharField(max_length=100)),
                ('tax_info', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('shelf_life', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('allergen', models.CharField(max_length=100)),
                ('highlights', models.CharField(max_length=100)),
                ('delivery_area', models.CharField(max_length=100)),
                ('delivery_slot', models.CharField(max_length=100)),
                ('return_policy', models.CharField(max_length=100)),
                ('business_minimum', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
