# Generated by Django 6.0.6 on 2026-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellm',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signins',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
