# Generated by Django 6.0.6 on 2026-06-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_sellm_video_url_alter_signins_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellm',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
