# Generated by Django 6.0.6 on 2026-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=100)),
                ('order', models.CharField(choices=[('One-time order', 'One-time order'), ('Daily subscription - save 15%', 'Daily subscription - save 15%'), ('Alternate day subscription - save 10%', 'Alternate day subscription - save 10%'), ('Business supply quotation', 'Business supply quotation')], max_length=100)),
                ('quantity', models.CharField(choices=[('1 bottle', '1 bottle'), ('2 bottles', '2 bottles'), ('4 bottles', '4 bottles'), ('10 bottles - bulk', '10 bottles - bulk')], max_length=100)),
            ],
        ),
    ]
