# Generated by Django 6.0.6 on 2026-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinm',
            name='cart',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='signinm',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
